[package]
name = "rust_station_13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.1"
bevy_quinnet = "0.9.0"
chrono = "0.4.38"
clap = { version = "4.5.13", features = ["derive"] }
fern = "0.6.2"
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
sys-info = "0.9.1"
toml = "0.8.19"
whoami = "1.5.1"

[build-dependencies]
clap = { version = "4.5.13", features = ["derive"] }
clap_complete = "4.5.12"
clap_complete_fig = "4.5.2"
clap_complete_nushell = "4.5.3"
clap_mangen = "0.2.23"
walkdir = "2.5.0"

