[package]
name = "rust_station_13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.1"
bevy_quinnet = "0.9.0"
clap = { version = "4.5.13", features = ["derive"] }

